### ISSUE TITLE
Unable to build the .jar files for the Databricks job and Databricks monitoring

### ISSUE THREAD

**Issue by slsu0424** [mspnp/azure-databricks-streaming-analytics#10]
I am trying to execute this code as provided in the instructions and am getting this error (running this in Ubuntu):

`root@sansu-SB2:/mnt/c/Users/sansu/azure-databricks-streaming-analytics/azure# docker run -it --rm -v 'pwd':/azure-databricks-streaming-analytics/azure -v ~/.m2:/root/.m2 maven:3.6.3-jdk-8 mvn -f /azure-databricks-streaming-analytics/azure/pom.xml package
POM file /azure-databricks-streaming-analytics/azure/pom.xml specified with the -f/--file command line argument does not exist
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /azure-databricks-streaming-analytics/azure/pom.xml: /azure-databricks-streaming-analytics/azure/pom.xml (No such file or directory) @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/azure-databricks-streaming-analytics/azure/pom.xml) has 1 error
[ERROR]     Non-readable POM /azure-databricks-streaming-analytics/azure/pom.xml: /azure-databricks-streaming-analytics/azure/pom.xml (No such file or directory)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
root@sansu-SB2:/mnt/c/Users/sansu/azure-databricks-streaming-analytics/azure#`

Would appreciate some guidance on how to resolve this error.

**Comment by hallihan** [comment]
It looks like your command is using a regular single quote characters `'` around `pwd` when it really need a backticks `` ` ``.  The backticks cause the shell to run enclosed command and return the result as a string to be used in the parent command line.  

Because `'pwd'` is being interpreted as a string here, Docker is attempting to mount the file/dir named `pwd` to this location in the container.  Docker doesn't produce an error for this, but if you run the command and replace the `mvn package` command with `bash`, you can poke around and see that within the container `/azure-databricks-streaming-analytics/azure` is empty.

Example command to troubleshoot what is happening inside the container: 
```bash
docker run -it --rm -v 'pwd':/azure-databricks-streaming-analytics/azure -v ~/.m2:/root/.m2 maven:3.6.3-jdk-8 bash
```
